version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: ./
      dockerfile: Dockerfile
#    command: gunicorn --bind 0.0.0.0:8000 website.wsgi
    volumes:
      - static_volume:/app/website/static
      - media_volume:/app/website/mediafiles
      - nginx_volume:/app/website/nginx
    expose:
      - 8000
    environment:
      - SECRET_KEY
      - TELEGRAMBOT_IP
      - TELEGRAMBOT_PORT
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/website/static
      - media_volume:/app/website/mediafiles
      - nginx_volume:/app/website/nginx
    ports:
      - "${WEBSITE_PORT_HTTPS}:443"
      - "${WEBSITE_PORT_HTTP}:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  nginx_volume: