# Generated by Django 4.1.1 on 2022-09-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(default=None, max_length=20, verbose_name='status')),
                ('phone', models.TextField(verbose_name='phone')),
                ('address', models.TextField(verbose_name='address')),
                ('pizza', models.TextField(verbose_name='pizza')),
            ],
        ),
    ]
